export enum JobSource {
  COMPANY_WEBSITE = 'COMPANY_WEBSITE',
  LINKEDIN = 'LINKEDIN',
  INDEED = 'INDEED',
  ICT_JOBS = 'ICT_JOBS',
  JOB_FAIR = 'JOB_FAIR',
  MOOVIJOB = 'MOOVIJOB',
  MONSTER = 'MONSTER',
  PUBLIC_EMPLOYMENT_SERVICE = 'PUBLIC_EMPLOYMENT_SERVICE',
  SOCIAL_MEDIA = 'SOCIAL_MEDIA',
  OTHER = 'OTHER',
}
