server:
  port: ${SERVER_PORT}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jobtracker
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    user:
      name: disabled
      password: disabled
    main:
      allow-bean-definition-overriding: true